name: Django Workflow Testing
on: workflow_dispatch
jobs:
  first-one:
    runs-on: ubuntu-latest, windows-latest, macos-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' #give specific version of python where your django project will run
      - name: Run the Project in hosted machine
        run: py manage.py runserver
